<?php

/**
 * @file
 * This is the install file.
 */

/**
 * Implements hook_schema().
 */
function product_menu_schema() {

  $schema['cart'] = [
    'description' => 'product cart',
    'fields' => [
      'user_id' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
      'product_id' => [
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
        'serialize' => TRUE,
      ],
    ],
    'primary key' => ['user_id'],
  ];

  return $schema;
}
